/**
 * One-time helper: downloads the brand fonts (Space Grotesk for headings,
 * Inter for body — same as the website) from Google Fonts as woff2, including
 * the latin-ext subset that carries Azerbaijani ə/Ə, ş, ğ, ı, ö, ü, ç.
 * Writes assets/fonts/*.woff2 + assets/fonts/fonts.css with @font-face rules.
 *
 * The downloaded files are meant to be kept in the repo so PDF generation
 * never needs the network. Re-run only if you change the font list below.
 *
 * Usage: node corporate-profile/tools/fetch-fonts.js
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const FONTS_DIR = path.resolve(__dirname, '..', 'assets', 'fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  { css: 'Space+Grotesk:wght@400;500;600;700', slug: 'space-grotesk' },
  { css: 'Inter:wght@400;500;600;700', slug: 'inter' },
];
const SUBSETS = ['latin', 'latin-ext'];

function get(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': UA } }, (res) => {
        if (res.statusCode !== 200) return reject(new Error(res.statusCode + ' ' + url));
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
      })
      .on('error', reject);
  });
}

async function main() {
  fs.mkdirSync(FONTS_DIR, { recursive: true });
  let cssOut = '/* Generated by tools/fetch-fonts.js — local brand fonts with latin-ext (Azerbaijani) */\n';

  for (const fam of FAMILIES) {
    const cssUrl = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
    const css = (await get(cssUrl)).toString('utf8');

    // Split into "/* subset */ @font-face {...}" blocks.
    const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g;
    let m;
    const seenFiles = new Set();
    while ((m = blockRe.exec(css)) !== null) {
      const subset = m[1];
      let block = m[2];
      if (!SUBSETS.includes(subset)) continue;

      const urlMatch = block.match(/url\((https:[^)]+\.woff2)\)/);
      const weightMatch = block.match(/font-weight:\s*([\d\s]+);/);
      if (!urlMatch) continue;
      const weight = (weightMatch ? weightMatch[1].trim() : '400').replace(/\s+/g, '-');
      const fileName = `${fam.slug}-${subset}-${weight}.woff2`;

      if (!seenFiles.has(fileName)) {
        seenFiles.add(fileName);
        const buf = await get(urlMatch[1]);
        fs.writeFileSync(path.join(FONTS_DIR, fileName), buf);
        console.log(`  ${fileName}  (${Math.round(buf.length / 1024)} KB)`);
      }
      block = block.replace(/src:[^;]+;/, `src: url('${fileName}') format('woff2');`);
      cssOut += `/* ${subset} */\n${block}\n`;
    }
  }

  fs.writeFileSync(path.join(FONTS_DIR, 'fonts.css'), cssOut, 'utf8');
  console.log('Wrote fonts.css');
}

main().catch((e) => {
  console.error('Font download failed:', e.message);
  console.error('The template falls back to system fonts (Segoe UI covers Azerbaijani).');
  process.exit(1);
});
